name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anushibin007/tomcat-jre11-openjdk-ssl:latest
    - name: Push the Docker image
      run: docker login -u anushibin007 -p ${{ secrets.DOCKER_TOKEN }} && docker push anushibin007/tomcat-jre11-openjdk-ssl:latest
